[package]
name = "sakkosekk"
version = "0.1.0"
authors = ["Arve Seljebu <arve.seljebu@gmail.com>"]
edition = "2018"

[dependencies]
rusqlite = { version = "0.20", features = ["bundled"] }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "database"
harness = false
